#-------------------------------------------
#  Clean data for the Floorplan UI.
#-------------------------------------------
#---Sensor for Time and Date.-----------------------------
- platform: template
  sensors:
    floorplan_date:
      friendly_name: 'Date'
      value_template: >-
        {{now().strftime("%A")}}, {{now().strftime("%B")}} {{now().strftime("%d")}}
- platform: template
  sensors:
    floorplan_time:
      friendly_name: 'Time'
      value_template: >-
        {{now().strftime("%I")}}:{{now().strftime("%M")}} {{now().strftime("%p")}}

- platform: template
  sensors:
    type_of_day:
      friendly_name: 'Type of Day'
      value_template: >-
        {%- if now().strftime("%A") == "Saturday" -%}
          Weekend
        {%- elif now().strftime("%A") == "Sunday" -%}
          Weekend
        {%- else -%}
          Weekday       
        {%- endif -%}

