#####################################################################
### Aeotec MultiSensor 6 Motion Detector status
#####################################################################
- platform: template
  sensors:
    motionsensor:
      value_template: >-
        {% set state = states('sensor.living_room_multisensor_burglar') %}
        {% if state == '8' %}
          Motion
        {% elif state == '0' %}
          Idle
        {% elif state == '3' %}
          Tamper
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Living Room Motion Sensor'

#####################################################################
### Aeotec Door/Window Sensor 6
#####################################################################
- platform: template
  sensors:
    front_door:
      value_template: >-
        {% set state = states('binary_sensor.front_door_sensor') %}
        {% if state == 'on' %}
          Open
        {% elif state == 'off' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Front Door Sensor'

- platform: template
  sensors:
    garage_entry_door:
      value_template: >-
        {% set state = states('binary_sensor.garage_entry_door_sensor') %}
        {% if state == 'on' %}
          Open
        {% elif state == 'off' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Garage Entry Door'

#####################################################################
### Aeotec Door/Window Sensor
#####################################################################
- platform: template
  sensors:
    den_window:
      value_template: >-
        {% set state = states('sensor.den_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Den Window'

- platform: template
  sensors:
    jayden_room_window:
      value_template: >-
        {% set state = states('sensor.jayden_room_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Jayden Room Window'

- platform: template
  sensors:
    back_door:
      value_template: >-
        {% set state = states('sensor.back_door_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Back Door'

- platform: template
  sensors:
    allie_room_window:
      value_template: >-
        {% set state = states('sensor.allie_room_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Allie Room Window'

#####################################################################
### iPhone
#####################################################################
- platform: template
  sensors:
    anthony_location:
      value_template: >-
        {% set state = states('device_tracker.anthonys_iphone') %}
        {% if state == 'home' %}
          home
        {% elif state == 'near_home' %}
          home
        {% else %}
          away
        {% endif %}
      friendly_name: 'Anthony'

- platform: template
  sensors:
    tawny_location:
      value_template: >-
        {% set state = states('device_tracker.tawnys_iphone') %}
        {% if state == 'home' %}
          home
        {% elif state == 'near_home' %}
          home
        {% else %}
          away
        {% endif %}
      friendly_name: 'Tawny'

#####################################################################
### Monoprice Door/Window Sensor
#####################################################################
- platform: template
  sensors:
    bonus_room_north_window:
      value_template: >-
        {% set state = states('sensor.bonus_room_north_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Bonus Room N Window'

- platform: template
  sensors:
    bonus_room_ne_window:
      value_template: >-
        {% set state = states('sensor.bonus_room_ne_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Bonus Room NE Window'

- platform: template
  sensors:
    bonus_room_se_window:
      value_template: >-
        {% set state = states('sensor.bonus_room_se_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Bonus Room SE Window'

- platform: template
  sensors:
    laundry_room_window:
      value_template: >-
        {% set state = states('sensor.laundry_room_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Laundry Room Window'

- platform: template
  sensors:
    dining_room_n_window:
      value_template: >-
        {% set state = states('sensor.dining_room_n_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Dining Room N Window'

- platform: template
  sensors:
    dining_room_s_window:
      value_template: >-
        {% set state = states('sensor.dining_room_s_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Dining Room S Window'

- platform: template
  sensors:
    living_room_e_window:
      value_template: >-
        {% set state = states('sensor.living_room_e_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Living Room E Window'

- platform: template
  sensors:
    living_room_se_window:
      value_template: >-
        {% set state = states('sensor.living_room_se_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Living Room SE Window'

- platform: template
  sensors:
    living_room_sw_window:
      value_template: >-
        {% set state = states('sensor.living_room_sw_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Living Room SW Window'

- platform: template
  sensors:
    master_bedroom_se_window:
      value_template: >-
        {% set state = states('sensor.master_bedroom_se_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Master Bedroom SE Window'

- platform: template
  sensors:
    master_bedroom_sw_window:
      value_template: >-
        {% set state = states('sensor.master_bedroom_sw_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Master Bedroom SW Window'

- platform: template
  sensors:
    master_bedroom_w_window:
      value_template: >-
        {% set state = states('sensor.master_bedroom_w_window_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Master Bedroom W Window'

- platform: template
  sensors:
   garage_attic_door:
      value_template: >-
        {% set state = states('sensor.garage_attic_door_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Garage Attic Door'

- platform: template
  sensors:
    master_closet_attic_door:
      value_template: >-
        {% set state = states('sensor.master_closet_attic_door_access_control') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Master Closet Attic Door'

#####################################################################
### Monoprice Garage Door Tilt Sensor
#####################################################################
- platform: template
  sensors:
    garage_door:
      value_template: >-
        {% set state = states('sensor.garage_door_alarm_level') %}
        {% if state == '255' %}
          Open
        {% elif state == '0' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Garage Door'








