#####################################################################
### Aeotec MultiSensor 6 Motion Detector status
#####################################################################
- platform: template
  sensors:
    motionsensor:
      value_template: >-
        {% set state = states('sensor.living_room_multisensor_burglar_5_10') %}
        {% if state == '8' %}
          Motion
        {% elif state == '0' %}
          Idle
        {% elif state == '3' %}
          Tamper
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Living Room Motion Sensor'

#####################################################################
### Aeotec Door/Window Sensor 6 Front Door status
#####################################################################
- platform: template
  sensors:
    frontdoorsensor:
      value_template: >-
        {% set state = states('binary_sensor.front_door_sensor_8_0') %}
        {% if state == 'on' %}
          Open
        {% elif state == 'off' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Front Door Sensor'

#####################################################################
### Aeotec Door/Window Sensor 6 Garage Door status
#####################################################################
- platform: template
  sensors:
    garagedoorsensor:
      value_template: >-
        {% set state = states('binary_sensor.garage_door_sensor_9_0') %}
        {% if state == 'on' %}
          Open
        {% elif state == 'off' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Garage Door Sensor'

- platform: template
  sensors:
    denwindowsensor:
      value_template: >-
        {% set state = states('sensor.den_window_access_control_12_9') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Den Window Sensor'

- platform: template
  sensors:
    jaydenwindowsensor:
      value_template: >-
        {% set state = states('sensor.jayden_room_window_access_control_16_9') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Jayden Window Sensor'

- platform: template
  sensors:
    backdoorsensor:
      value_template: >-
        {% set state = states('sensor.back_door_access_control_14_9') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Back Door Sensor'

- platform: template
  sensors:
    alliewindowsensor:
      value_template: >-
        {% set state = states('sensor.allie_room_window_access_control_15_9') %}
        {% if state == '22' %}
          Open
        {% elif state == '23' %}
          Closed
        {% else %}
          {{ state }}
        {% endif %}
      friendly_name: 'Allie Window Sensor'


- platform: template
  sensors:
    anthony_location:
      value_template: >-
        {% set state = states('device_tracker.anthonys_iphone') %}
        {% if state == 'home' %}
          home
        {% elif state == 'near_home' %}
          home
        {% else %}
          away
        {% endif %}
      friendly_name: 'Anthony'

- platform: template
  sensors:
    tawny_location:
      value_template: >-
        {% set state = states('device_tracker.tawnys_iphone') %}
        {% if state == 'home' %}
          home
        {% elif state == 'near_home' %}
          home
        {% else %}
          away
        {% endif %}
      friendly_name: 'Tawny'






