###############################################
###
### ALARM
###
###############################################
- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: sensor.motionsensor
      to: 'Motion'
    - platform: state
      entity_id: sensor.front_door
      to: 'Open'
    - platform: state
      entity_id: sensor.garage_entry_door
      to: 'Open'
    - platform: state
      entity_id: sensor.back_door
      to: 'Open'
    - platform: state
      entity_id: sensor.den_window
      to: 'Open'
    - platform: state
      entity_id: sensor.jayden_room_window
      to: 'Open'
    - platform: state
      entity_id: sensor.allie_room_window
      to: 'Open'
    - platform: state
      entity_id: sensor.master_closet_attic_door
      to: 'Open'
    - platform: state
      entity_id: sensor.garage_attic_door
      to: 'Open'
    - platform: state
      entity_id: sensor.bonus_room_north_window
      to: 'Open'
    - platform: state
      entity_id: sensor.bonus_room_ne_window
      to: 'Open'
    - platform: state
      entity_id: sensor.bonus_room_se_window
      to: 'Open'
    - platform: state
      entity_id: sensor.laundry_room_window
      to: 'Open'
    - platform: state
      entity_id: sensor.dining_room_n_window
      to: 'Open'
    - platform: state
      entity_id: sensor.dining_room_s_window
      to: 'Open'
    - platform: state
      entity_id: sensor.living_room_e_window
      to: 'Open'
    - platform: state
      entity_id: sensor.living_room_se_window
      to: 'Open'
    - platform: state
      entity_id: sensor.living_room_sw_window
      to: 'Open'
    - platform: state
      entity_id: sensor.master_bedroom_se_window
      to: 'Open'
    - platform: state
      entity_id: sensor.master_bedroom_sw_window
      to: 'Open'
    - platform: state
      entity_id: sensor.master_bedroom_w_window
      to: 'Open'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
    - service: notify.all
      data_template:
        title: "ALARM "
        message: "Alarm triggered by {{ trigger.to_state.attributes.friendly_name }}"
        data:
          push:
            category: "ALARM"

- alias: 'Trigger alarm while armed home'
  trigger:
    - platform: state
      entity_id: sensor.front_door
      to: 'Open'
    - platform: state
      entity_id: sensor.garage_entry_door
      to: 'Open'
    - platform: state
      entity_id: sensor.back_door
      to: 'Open'
    - platform: state
      entity_id: sensor.den_window
      to: 'Open'
    - platform: state
      entity_id: sensor.jayden_room_window
      to: 'Open'
    - platform: state
      entity_id: sensor.allie_room_window
      to: 'Open'
    - platform: state
      entity_id: sensor.master_closet_attic_door
      to: 'Open'
    - platform: state
      entity_id: sensor.garage_attic_door
      to: 'Open'
    - platform: state
      entity_id: sensor.bonus_room_north_window
      to: 'Open'
    - platform: state
      entity_id: sensor.bonus_room_ne_window
      to: 'Open'
    - platform: state
      entity_id: sensor.bonus_room_se_window
      to: 'Open'
    - platform: state
      entity_id: sensor.laundry_room_window
      to: 'Open'
    - platform: state
      entity_id: sensor.dining_room_n_window
      to: 'Open'
    - platform: state
      entity_id: sensor.dining_room_s_window
      to: 'Open'
    - platform: state
      entity_id: sensor.living_room_e_window
      to: 'Open'
    - platform: state
      entity_id: sensor.living_room_se_window
      to: 'Open'
    - platform: state
      entity_id: sensor.living_room_sw_window
      to: 'Open'
    - platform: state
      entity_id: sensor.master_bedroom_se_window
      to: 'Open'
    - platform: state
      entity_id: sensor.master_bedroom_sw_window
      to: 'Open'
    - platform: state
      entity_id: sensor.master_bedroom_w_window
      to: 'Open'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
    - service: notify.all
      data_template:
        title: "ALARM "
        message: "Alarm triggered by {{ trigger.to_state.attributes.friendly_name }}"
        data:
          push:
            category: "ALARM"

- alias: 'Siren when alarm triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: switch.turn_on
      entity_id: switch.siren_switch

- alias: 'Siren off when disarmed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'disarmed'
  action:
    - service: switch.turn_off
      entity_id: switch.siren_switch

###############################################
###
### iOS App ALARM CONTROL
###
###############################################
- alias: 'iOS Silence Alarm'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SILENCE_ALARM
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

###############################################
###
### PRESENCE ALARM CONTROL
###
###############################################
- alias: 'Arm when away'
  trigger:
    - platform: state
      entity_id: sensor.anthony_location
      from: 'home'
      to: 'away'
    - platform: state
      entity_id: sensor.tawny_location
      from: 'home'
      to: 'away'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: sensor.anthony_location
       state: 'away'
     - condition: state
       entity_id: sensor.tawny_location
       state: 'away'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code
    - service: notify.all
      data:
        message: "No one home, alarm armed"

- alias: 'Disarm when home'
  trigger:
    - platform: state
      entity_id: sensor.anthony_location
      from: 'away'
      to: 'home'
    - platform: state
      entity_id: sensor.tawny_location
      from: 'away'
      to: 'home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code
    - service: notify.all
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} arrived home, alarm disarmed"

- alias: 'Notify when garage door opens'
  trigger:
    - platform: state
      entity_id: sensor.garage_door
      to: 'Open'
  action:
    - service: notify.all
      data:
        message: "Garage door opened"



###############################################
###
### TIME ALARM CONTROL
###
###############################################
- alias: 'Arm for evening when home'
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    condition: or
    conditions:
     - condition: state
       entity_id: sensor.anthony_location
       state: 'home'
     - condition: state
       entity_id: sensor.tawny_location
       state: 'home'
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: 'Disarm for morning when home'
  trigger:
    - platform: time
      at: '06:00:00'
  condition:
    condition: or
    conditions:
     - condition: state
       entity_id: sensor.anthony_location
       state: 'home'
     - condition: state
       entity_id: sensor.tawny_location
       state: 'home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code




